name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Show build outputs (Debugging)
        run: ls -R .

      - name: Find APKs (Debugging)
        run: find . -type f -name "*.apk" || true

      - name: Upload all APKs
