name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # नया Step - APK search
      - name: Search for APKs
        run: |
          echo "Searching for APK files..."
          find . -type f -name "*.apk"

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: '**/*.apk'
