name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle assembleDebug (via Gradle Action)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug

      - name: Find APKs
        run: |
          echo "Looking for APKs:"
          find . -type f -name "*.apk" || true

      - name: Upload all APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: '**/*.apk'
